var json_gc_olds = [
  {
    "Code": "GC2D4",
    "Placed": "18/2/2001",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Montserrat",
    "Found_by_me": "21/4/2017",
    "Placed By": "Francesc-Coral-Brian-Carles",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 3,
    "Tern": 3.5,
    "Favorite points": 324,
    "Kms": 38.98,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.610317,
    "Longitude": 1.786483
  },
  {
    "Code": "GC1A7A",
    "Placed": "2/9/2001",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Montcau",
    "Found_by_me": "15/2/2020",
    "Placed By": "joanmire",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 50,
    "Kms": 32.13,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.67935,
    "Longitude": 2.0042
  },
  {
    "Code": "GC1AAA",
    "Placed": "3/9/2001",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Costa Brava I (Ses Felugues)",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 73,
    "Kms": 102.51,
    "Country": "Spain",
    "User Data 4": "Baix Empordà",
    ".": 0,
    "Latitude": 41.93235,
    "Longitude": 3.210967
  },
  {
    "Code": "GC2245",
    "Placed": "13/10/2001",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Ull de Ter",
    "Found_by_me": "23/7/2022",
    "Placed By": "Jordi Jr, Montse, Jordi, Mike, Neil and Paul",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2.5,
    "Favorite points": 28,
    "Kms": 111.2,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.42155,
    "Longitude": 2.252117
  },
  {
    "Code": "GC244F",
    "Placed": "24/10/2001",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Costa Brava II (Roca Foradada)",
    "Found_by_me": "3/4/2022",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 90,
    "Kms": 111.47,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.07495,
    "Longitude": 3.202717
  },
  {
    "Code": "GC258B",
    "Placed": "28/10/2001",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Ridaura",
    "Found_by_me": "",
    "Placed By": "Joan i Quim (joanmire team)",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 3.5,
    "Tern": 4,
    "Favorite points": 30,
    "Kms": 85.42,
    "Country": "Spain",
    "User Data 4": "Garrotxa",
    ".": 0,
    "Latitude": 42.178367,
    "Longitude": 2.368983
  },
  {
    "Code": "GC3F27",
    "Placed": "3/3/2002",
    "Corrected Coordinates Indicator": "C",
    "Cache_type": "Multicache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Parc Güell",
    "Found_by_me": "23/1/2021",
    "Placed By": "joanmire",
    "Elevation": 0,
    "Container": "Small",
    "Diff": 2,
    "Tern": 2.5,
    "Favorite points": 218,
    "Kms": 2.48,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.41845,
    "Longitude": 2.153033333333333
  },
  {
    "Code": "GC4288",
    "Placed": "16/3/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "A piece of Canada in Spain.",
    "Found_by_me": "",
    "Placed By": "Quiet-Tiger",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 35,
    "Kms": 30.66,
    "Country": "Spain",
    "User Data 4": "Garraf",
    ".": 0,
    "Latitude": 41.250833,
    "Longitude": 1.8952
  },
  {
    "Code": "GC4FA5",
    "Placed": "21/4/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Cardó Spa",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 4,
    "Favorite points": 29,
    "Kms": 143.52,
    "Country": "Spain",
    "User Data 4": "Baix Ebre",
    ".": 0,
    "Latitude": 40.945783,
    "Longitude": 0.588567
  },
  {
    "Code": "GC5251",
    "Placed": "28/4/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Norfeu",
    "Found_by_me": "22/5/2021",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 75,
    "Kms": 127.18,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.242333,
    "Longitude": 3.253167
  },
  {
    "Code": "GC5A26",
    "Placed": "20/5/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Virtual Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Barcelona",
    "Found_by_me": "18/7/2020",
    "Placed By": "Yellow Jacket and Lectro",
    "Elevation": 0,
    "Container": "Virtual",
    "Diff": 1,
    "Tern": 1,
    "Favorite points": 330,
    "Kms": 5.29,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.421833,
    "Longitude": 2.118783
  },
  {
    "Code": "GC6603",
    "Placed": "1/6/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Taragonna Aquaduct",
    "Found_by_me": "23/8/2020",
    "Placed By": "FAMARA & jimmonty",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 1,
    "Tern": 1,
    "Favorite points": 122,
    "Kms": 84.19,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.1472,
    "Longitude": 1.243783
  },
  {
    "Code": "GC6604",
    "Placed": "1/6/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Virtual Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Castle Unknown",
    "Found_by_me": "",
    "Placed By": "Amagat per jimmonty i adoptat per crtn i nastrud",
    "Elevation": 0,
    "Container": "Virtual",
    "Diff": 1,
    "Tern": 2,
    "Favorite points": 23,
    "Kms": 61.15,
    "Country": "Spain",
    "User Data 4": "Anoia",
    ".": 0,
    "Latitude": 41.5136,
    "Longitude": 1.458317
  },
  {
    "Code": "GC64C9",
    "Placed": "16/6/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Gavarres",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 6,
    "Kms": 87.21,
    "Country": "Spain",
    "User Data 4": "GironËs",
    ".": 0,
    "Latitude": 41.9731,
    "Longitude": 2.930833
  },
  {
    "Code": "GC7FA1",
    "Placed": "15/8/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "El Corredor",
    "Found_by_me": "24/4/2022",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2.5,
    "Tern": 2,
    "Favorite points": 5,
    "Kms": 33.49,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.62495,
    "Longitude": 2.480467
  },
  {
    "Code": "GC8620",
    "Placed": "28/8/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Segarra I",
    "Found_by_me": "28/8/2020",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 37,
    "Kms": 78.31,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.861533,
    "Longitude": 1.444933
  },
  {
    "Code": "GC8CE3",
    "Placed": "7/9/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Banyoles",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 14,
    "Kms": 88.55,
    "Country": "Spain",
    "User Data 4": "Pla de l'Estany",
    ".": 0,
    "Latitude": 42.11045,
    "Longitude": 2.720817
  },
  {
    "Code": "GC92DD",
    "Placed": "21/9/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Fontcalda",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 3,
    "Tern": 3,
    "Favorite points": 29,
    "Kms": 153.97,
    "Country": "Spain",
    "User Data 4": "Terra Alta",
    ".": 0,
    "Latitude": 40.99825,
    "Longitude": 0.430233
  },
  {
    "Code": "GC9285",
    "Placed": "21/9/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "El tresor de Tivissa",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2.5,
    "Tern": 2,
    "Favorite points": 39,
    "Kms": 133.12,
    "Country": "Spain",
    "User Data 4": "Ribera d'Ebre",
    ".": 0,
    "Latitude": 41.060617,
    "Longitude": 0.6647
  },
  {
    "Code": "GC9AC9",
    "Placed": "12/10/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Didjeridoo Matagalls",
    "Found_by_me": "7/12/2018",
    "Placed By": "joanmire",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 34,
    "Kms": 46.56,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.82125,
    "Longitude": 2.354717
  },
  {
    "Code": "GCA107",
    "Placed": "26/10/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Collsacabra",
    "Found_by_me": "28/6/2020",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2.5,
    "Favorite points": 27,
    "Kms": 75.06,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.0769,
    "Longitude": 2.406167
  },
  {
    "Code": "GCA1EF",
    "Placed": "27/10/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "NFFF",
    "Waypoint_Name": "Fageda d'en Jordà",
    "Found_by_me": "",
    "Placed By": "Maria,Adria,Marta,Carmen,Artur y Joan",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 3,
    "Tern": 2,
    "Favorite points": 32,
    "Kms": 85.16,
    "Country": "Spain",
    "User Data 4": "Garrotxa",
    ".": 0,
    "Latitude": 42.147617,
    "Longitude": 2.5143
  },
  {
    "Code": "GCAC6E",
    "Placed": "23/11/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Cadiretes",
    "Found_by_me": "16/10/2021",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2.5,
    "Favorite points": 40,
    "Kms": 72.36,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.757517,
    "Longitude": 2.928467
  },
  {
    "Code": "GCB230",
    "Placed": "7/12/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Burriac's Treasure",
    "Found_by_me": "7/1/2022",
    "Placed By": "EB/G1IVG",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2.5,
    "Tern": 3.5,
    "Favorite points": 32,
    "Kms": 21.28,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.537533,
    "Longitude": 2.386717
  },
  {
    "Code": "GCB6AE",
    "Placed": "20/12/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Santa Llúcia de Puigmal",
    "Found_by_me": "",
    "Placed By": "andreu (Llebra Maintain)",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 1.5,
    "Favorite points": 14,
    "Kms": 90.16,
    "Country": "Spain",
    "User Data 4": "Garrotxa",
    ".": 0,
    "Latitude": 42.217437,
    "Longitude": 2.399432
  },
  {
    "Code": "GCB8F0",
    "Placed": "26/12/2002",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "La Talaia (El Pi de les 3 branques)",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 23,
    "Kms": 60.35,
    "Country": "Spain",
    "User Data 4": "Baix PenedËs",
    ".": 0,
    "Latitude": 41.337867,
    "Longitude": 1.467733
  },
  {
    "Code": "GCBD92",
    "Placed": "3/1/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Unknown Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Pira Basto de Lluc",
    "Found_by_me": "",
    "Placed By": "raorpig",
    "Elevation": 0,
    "Container": "Unknown",
    "Diff": 1,
    "Tern": 2,
    "Favorite points": 7,
    "Kms": 81.97,
    "Country": "Spain",
    "User Data 4": "Conca de Barberà",
    ".": 0,
    "Latitude": 41.4332,
    "Longitude": 1.199117
  },
  {
    "Code": "GCC94A",
    "Placed": "24/1/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Foix",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2.5,
    "Favorite points": 16,
    "Kms": 48.6,
    "Country": "Spain",
    "User Data 4": "Alt PenedËs",
    ".": 0,
    "Latitude": 41.25965,
    "Longitude": 1.642183
  },
  {
    "Code": "GCD9AE",
    "Placed": "23/2/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFX",
    "Waypoint_Name": "Sapera",
    "Found_by_me": "27/11/2022",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3.5,
    "Favorite points": 40,
    "Kms": 30.2,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.643733,
    "Longitude": 1.970867
  },
  {
    "Code": "GCF493",
    "Placed": "7/4/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FNFF",
    "Waypoint_Name": "Durro",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2,
    "Favorite points": 28,
    "Kms": 164.54,
    "Country": "Spain",
    "User Data 4": "Alta Ribagorça",
    ".": 0,
    "Latitude": 42.4953,
    "Longitude": 0.810983
  },
  {
    "Code": "GCFE44",
    "Placed": "16/4/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FNFF",
    "Waypoint_Name": "Mont-Rebei",
    "Found_by_me": "22/1/2022",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 4,
    "Favorite points": 76,
    "Kms": 144.23,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.077917,
    "Longitude": 0.681483
  },
  {
    "Code": "GCG6X3",
    "Placed": "31/5/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Tavertet's Treasure",
    "Found_by_me": "3/7/2022",
    "Placed By": "EB/G1IVG",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 4,
    "Favorite points": 15,
    "Kms": 64.78,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.983133,
    "Longitude": 2.396117
  },
  {
    "Code": "GCGDT7",
    "Placed": "24/6/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Museo de las Ciencias CLM 6",
    "Found_by_me": "23/5/2021",
    "Placed By": "mccm",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 3,
    "Tern": 3,
    "Favorite points": 19,
    "Kms": 135.91,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.322183,
    "Longitude": 3.29395
  },
  {
    "Code": "GCGCQ4",
    "Placed": "1/7/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Castillo de MontornËs del VallËs",
    "Found_by_me": "4/6/2022",
    "Placed By": "garri",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 3,
    "Tern": 3,
    "Favorite points": 17,
    "Kms": 13.93,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.528433,
    "Longitude": 2.272333
  },
  {
    "Code": "GC200RK",
    "Placed": "20/7/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Castell de Montjuïc (Barcelona) reload.",
    "Found_by_me": "29/6/2010",
    "Placed By": "Racoseral (Reposición del anterior)",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 1.5,
    "Tern": 1.5,
    "Favorite points": 145,
    "Kms": 7.17,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.360317,
    "Longitude": 2.161567
  },
  {
    "Code": "GCGJVV",
    "Placed": "3/8/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Tordera l'Erola",
    "Found_by_me": "28/1/2023",
    "Placed By": "sorgonet.com",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 6,
    "Kms": 46.88,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.671367,
    "Longitude": 2.6373
  },
  {
    "Code": "GCGP8V",
    "Placed": "13/8/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Multicache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "El Montgrí",
    "Found_by_me": "",
    "Placed By": "Landyman & family",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3.5,
    "Favorite points": 82,
    "Kms": 105.36,
    "Country": "Spain",
    "User Data 4": "Baix Empordà",
    ".": 0,
    "Latitude": 42.052017,
    "Longitude": 3.131667
  },
  {
    "Code": "GCGN4R",
    "Placed": "14/8/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFNN",
    "Waypoint_Name": "Castell de Verdera",
    "Found_by_me": "24/5/2021",
    "Placed By": "garri",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2.5,
    "Tern": 3.5,
    "Favorite points": 78,
    "Kms": 128.83,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.319033,
    "Longitude": 3.16845
  },
  {
    "Code": "GCGR7T",
    "Placed": "25/8/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Prat de Cadí",
    "Found_by_me": "12/6/2021",
    "Placed By": "amon",
    "Elevation": 0,
    "Container": "Unknown",
    "Diff": 1.5,
    "Tern": 3,
    "Favorite points": 21,
    "Kms": 106.04,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.294167,
    "Longitude": 1.66145
  },
  {
    "Code": "GCGR1C",
    "Placed": "26/8/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Estanys de la Pera",
    "Found_by_me": "",
    "Placed By": "Andreu",
    "Elevation": 0,
    "Container": "Unknown",
    "Diff": 2,
    "Tern": 4,
    "Favorite points": 19,
    "Kms": 124.59,
    "Country": "Spain",
    "User Data 4": "Cerdanya",
    ".": 0,
    "Latitude": 42.455783,
    "Longitude": 1.59825
  },
  {
    "Code": "GCGWZY",
    "Placed": "11/9/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Balsareny",
    "Found_by_me": "3/2/2020",
    "Placed By": "tecnics",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 1.5,
    "Tern": 1.5,
    "Favorite points": 23,
    "Kms": 55.65,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.870217,
    "Longitude": 1.8818
  },
  {
    "Code": "GCGX0C",
    "Placed": "11/9/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFNF",
    "Waypoint_Name": "La Patum",
    "Found_by_me": "8/2/2009",
    "Placed By": "tecnics",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2.5,
    "Tern": 2.5,
    "Favorite points": 25,
    "Kms": 81.99,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.109733,
    "Longitude": 1.8224
  },
  {
    "Code": "GCGX71",
    "Placed": "15/9/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Montsià",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 12,
    "Kms": 160.69,
    "Country": "Spain",
    "User Data 4": "Montsià",
    ".": 0,
    "Latitude": 40.655133,
    "Longitude": 0.558917
  },
  {
    "Code": "GCGXF8",
    "Placed": "17/9/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "NNNN",
    "Waypoint_Name": "Scala Dei",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 1.5,
    "Tern": 1.5,
    "Favorite points": 20,
    "Kms": 116.12,
    "Country": "Spain",
    "User Data 4": "Priorat",
    ".": 0,
    "Latitude": 41.258,
    "Longitude": 0.808633
  },
  {
    "Code": "GCGY3E",
    "Placed": "21/9/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Pallejà",
    "Found_by_me": "",
    "Placed By": "tecnics",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 1,
    "Tern": 1.5,
    "Favorite points": 13,
    "Kms": 16.29,
    "Country": "Spain",
    "User Data 4": "Baix Llobregat",
    ".": 0,
    "Latitude": 41.418667,
    "Longitude": 1.986883
  },
  {
    "Code": "GCH0EH",
    "Placed": "4/10/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Carrasumada",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2.5,
    "Favorite points": 5,
    "Kms": 135.47,
    "Country": "Spain",
    "User Data 4": "Segrià",
    ".": 0,
    "Latitude": 41.515617,
    "Longitude": 0.56095
  },
  {
    "Code": "GCH0P8",
    "Placed": "5/10/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Pieza de Artilleria",
    "Found_by_me": "26/7/2011",
    "Placed By": "garri",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 4,
    "Tern": 2.5,
    "Favorite points": 305,
    "Kms": 111.56,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.093133,
    "Longitude": 3.183067
  },
  {
    "Code": "GCH0KA",
    "Placed": "5/10/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Sant Miquel de la Roca",
    "Found_by_me": "",
    "Placed By": "karles",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 47,
    "Kms": 98.19,
    "Country": "Spain",
    "User Data 4": "Pla de l'Estany",
    ".": 0,
    "Latitude": 42.18435,
    "Longitude": 2.782067
  },
  {
    "Code": "GCH1AB",
    "Placed": "8/10/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "La fita alta",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 1.5,
    "Tern": 2,
    "Favorite points": 6,
    "Kms": 113.48,
    "Country": "Spain",
    "User Data 4": "Pla d'Urgell",
    ".": 0,
    "Latitude": 41.612933,
    "Longitude": 0.843
  },
  {
    "Code": "GCH8TR",
    "Placed": "22/11/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "La Bófia",
    "Found_by_me": "8/5/2021",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 12,
    "Kms": 98.59,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.162233,
    "Longitude": 1.525633
  },
  {
    "Code": "GCHAZW",
    "Placed": "30/11/2003",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Tagamanent",
    "Found_by_me": "8/12/2020",
    "Placed By": "garri",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3.5,
    "Favorite points": 26,
    "Kms": 37.32,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.747717,
    "Longitude": 2.29515
  },
  {
    "Code": "GCHEVW",
    "Placed": "3/1/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Els Carcaixells",
    "Found_by_me": "13/11/2022",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 4.5,
    "Favorite points": 82,
    "Kms": 76.71,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.795233,
    "Longitude": 2.958917
  },
  {
    "Code": "GCHMW8",
    "Placed": "7/2/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Castell de St Miquel (Girona)",
    "Found_by_me": "",
    "Placed By": "karles",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2,
    "Favorite points": 19,
    "Kms": 85.85,
    "Country": "Spain",
    "User Data 4": "GironËs",
    ".": 0,
    "Latitude": 42.004717,
    "Longitude": 2.862133
  },
  {
    "Code": "GCHPWT",
    "Placed": "8/2/2004",
    "Corrected Coordinates Indicator": "C",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Les Escaules",
    "Found_by_me": "",
    "Placed By": "karles",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2,
    "Favorite points": 14,
    "Kms": 115.21,
    "Country": "Spain",
    "User Data 4": "Alt Empordà",
    ".": 0,
    "Latitude": 42.319,
    "Longitude": 2.8806666666666665
  },
  {
    "Code": "GCHQAN",
    "Placed": "20/2/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Navàs",
    "Found_by_me": "19/9/2010",
    "Placed By": "pelaroques",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 3,
    "Tern": 2,
    "Favorite points": 18,
    "Kms": 60.57,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.89405,
    "Longitude": 1.816233
  },
  {
    "Code": "GCHQVY",
    "Placed": "22/2/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Rocacorba",
    "Found_by_me": "16/5/2021",
    "Placed By": "karles",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2,
    "Favorite points": 21,
    "Kms": 82.89,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.065283,
    "Longitude": 2.689083
  },
  {
    "Code": "GCHRRQ",
    "Placed": "27/2/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Land Rover Best 4x4xFAR",
    "Found_by_me": "",
    "Placed By": "Jogibogi",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2,
    "Favorite points": 15,
    "Kms": 102.73,
    "Country": "Spain",
    "User Data 4": "Garrotxa",
    ".": 0,
    "Latitude": 42.286983,
    "Longitude": 2.621117
  },
  {
    "Code": "GCHTCB",
    "Placed": "29/2/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Cingles de Berti",
    "Found_by_me": "21/3/2021",
    "Placed By": "Valldeix",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 3.5,
    "Tern": 1.5,
    "Favorite points": 5,
    "Kms": 33.07,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.717967,
    "Longitude": 2.2318
  },
  {
    "Code": "GCHVXZ",
    "Placed": "7/3/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Webcam Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Pirineus",
    "Found_by_me": "13/6/2021",
    "Placed By": "tecnics",
    "Elevation": 0,
    "Container": "Virtual",
    "Diff": 1,
    "Tern": 1,
    "Favorite points": 117,
    "Kms": 115.72,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.443183,
    "Longitude": 1.90625
  },
  {
    "Code": "GCHYG4",
    "Placed": "7/3/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Castell de Lluçà",
    "Found_by_me": "23/10/2010",
    "Placed By": "pelaroques",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2,
    "Favorite points": 15,
    "Kms": 71.18,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.054267,
    "Longitude": 2.040333
  },
  {
    "Code": "GCJE68",
    "Placed": "6/4/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Soldados de Salamina",
    "Found_by_me": "30/7/2010",
    "Placed By": "Obrint Pas Team",
    "Elevation": 0,
    "Container": "Other",
    "Diff": 1.5,
    "Tern": 2.5,
    "Favorite points": 12,
    "Kms": 92.15,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.16655,
    "Longitude": 2.6728
  },
  {
    "Code": "GCJ6VH",
    "Placed": "11/4/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Pinturas rupestres Cabra-Feixet",
    "Found_by_me": "",
    "Placed By": "ninus",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 3,
    "Tern": 4,
    "Favorite points": 10,
    "Kms": 142.36,
    "Country": "Spain",
    "User Data 4": "Baix Ebre",
    ".": 0,
    "Latitude": 40.894967,
    "Longitude": 0.632917
  },
  {
    "Code": "GCJ6JV",
    "Placed": "14/4/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "NFFF",
    "Waypoint_Name": "Cova del Moro",
    "Found_by_me": "20/9/2020",
    "Placed By": "andreu",
    "Elevation": 0,
    "Container": "Unknown",
    "Diff": 1.5,
    "Tern": 3,
    "Favorite points": 20,
    "Kms": 40.23,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.780233,
    "Longitude": 2.257967
  },
  {
    "Code": "GCJ95Q",
    "Placed": "18/4/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "L'Estartit",
    "Found_by_me": "3/4/2022",
    "Placed By": "pelaroques",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3.5,
    "Favorite points": 42,
    "Kms": 110.74,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.056483,
    "Longitude": 3.2119
  },
  {
    "Code": "GCJAZR",
    "Placed": "25/4/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Gombren (Cascades)",
    "Found_by_me": "25/10/2020",
    "Placed By": "Covacha",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3.5,
    "Favorite points": 23,
    "Kms": 87.46,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.208133,
    "Longitude": 2.1207
  },
  {
    "Code": "GCJBW9",
    "Placed": "2/5/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "La Quar de Berguedà",
    "Found_by_me": "5/2/2020",
    "Placed By": "pelaroques",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2.5,
    "Tern": 4,
    "Favorite points": 11,
    "Kms": 77.75,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.104533,
    "Longitude": 1.973033
  },
  {
    "Code": "GCJD8F",
    "Placed": "9/5/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFNF",
    "Waypoint_Name": "El Graó, Calafell",
    "Found_by_me": "",
    "Placed By": "manel Lanzón",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 3,
    "Tern": 3,
    "Favorite points": 23,
    "Kms": 55.34,
    "Country": "Spain",
    "User Data 4": "Baix PenedËs",
    ".": 0,
    "Latitude": 41.19915,
    "Longitude": 1.59035
  },
  {
    "Code": "GCJWG0",
    "Placed": "25/6/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Pic Quartiules (near)",
    "Found_by_me": "",
    "Placed By": "ninus",
    "Elevation": 0,
    "Container": "Unknown",
    "Diff": 2,
    "Tern": 4,
    "Favorite points": 7,
    "Kms": 158.79,
    "Country": "Spain",
    "User Data 4": "Pallars Sobirà",
    ".": 0,
    "Latitude": 42.5931,
    "Longitude": 1.080517
  },
  {
    "Code": "GCJZE7",
    "Placed": "12/7/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Multicache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Nebraska Spot",
    "Found_by_me": "20/2/2021",
    "Placed By": "Carleenp and Garri",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 1.5,
    "Tern": 2.5,
    "Favorite points": 29,
    "Kms": 5.65,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.470283,
    "Longitude": 2.206583
  },
  {
    "Code": "GCJZAQ",
    "Placed": "12/7/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "La espiral Crop Circle.",
    "Found_by_me": "23/8/2020",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2,
    "Favorite points": 9,
    "Kms": 50.68,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.686383,
    "Longitude": 1.68525
  },
  {
    "Code": "GCK3A7",
    "Placed": "24/7/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "NFFF",
    "Waypoint_Name": "Cova d'Anes",
    "Found_by_me": "13/6/2021",
    "Placed By": "tecnics",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 4,
    "Tern": 4.5,
    "Favorite points": 47,
    "Kms": 112.16,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.381217,
    "Longitude": 1.759433
  },
  {
    "Code": "GCK3DE",
    "Placed": "25/7/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Besiberri",
    "Found_by_me": "",
    "Placed By": "amon",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 1,
    "Tern": 5,
    "Favorite points": 21,
    "Kms": 173.17,
    "Country": "Spain",
    "User Data 4": "Alta Ribagorça",
    ".": 0,
    "Latitude": 42.603567,
    "Longitude": 0.815217
  },
  {
    "Code": "GCK3MW",
    "Placed": "27/7/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Rebufa Bol!",
    "Found_by_me": "24/5/2021",
    "Placed By": "garri",
    "Elevation": 0,
    "Container": "Micro",
    "Diff": 2,
    "Tern": 4,
    "Favorite points": 42,
    "Kms": 132.54,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.353333,
    "Longitude": 3.1829
  },
  {
    "Code": "GCK8FM",
    "Placed": "12/8/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Vall d'Hortmoier",
    "Found_by_me": "",
    "Placed By": "karles",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 11,
    "Kms": 101.74,
    "Country": "Spain",
    "User Data 4": "Garrotxa",
    ".": 0,
    "Latitude": 42.296933,
    "Longitude": 2.5456
  },
  {
    "Code": "GCKA1J",
    "Placed": "17/8/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "L'Empordanet",
    "Found_by_me": "",
    "Placed By": "karles",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 11,
    "Kms": 101.52,
    "Country": "Spain",
    "User Data 4": "Baix Empordà",
    ".": 0,
    "Latitude": 41.960617,
    "Longitude": 3.170267
  },
  {
    "Code": "GCKBF7",
    "Placed": "22/8/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Torre de vigia Puigcabrer",
    "Found_by_me": "",
    "Placed By": "raorpig",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3.5,
    "Favorite points": 7,
    "Kms": 83.55,
    "Country": "Spain",
    "User Data 4": "Alt Camp",
    ".": 0,
    "Latitude": 41.3153,
    "Longitude": 1.191283
  },
  {
    "Code": "GCKCN3",
    "Placed": "26/8/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FNFF",
    "Waypoint_Name": "El Guarà Català",
    "Found_by_me": "23/3/2019",
    "Placed By": "garri",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2.5,
    "Tern": 4,
    "Favorite points": 52,
    "Kms": 106.99,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.383833,
    "Longitude": 2.116717
  },
  {
    "Code": "GCKK1F",
    "Placed": "18/9/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Finestres",
    "Found_by_me": "17/10/2020",
    "Placed By": "Alice & Alpha",
    "Elevation": 0,
    "Container": "Micro",
    "Diff": 1.5,
    "Tern": 3,
    "Favorite points": 17,
    "Kms": 83.92,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.1125,
    "Longitude": 2.593217
  },
  {
    "Code": "GCKNG3",
    "Placed": "27/9/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Multicache",
    "User flag": "",
    "lg": "NNFF",
    "Waypoint_Name": "Cala Pedrosa",
    "Found_by_me": "",
    "Placed By": "karles",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 3,
    "Tern": 3,
    "Favorite points": 28,
    "Kms": 100.78,
    "Country": "Spain",
    "User Data 4": "Baix Empordà",
    ".": 0,
    "Latitude": 41.90855,
    "Longitude": 3.206617
  },
  {
    "Code": "GCKQB6",
    "Placed": "4/10/2004",
    "Corrected Coordinates Indicator": "C",
    "Cache_type": "Unknown Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Barcelona Death",
    "Found_by_me": "",
    "Placed By": "tecnics",
    "Elevation": 0,
    "Container": "Micro",
    "Diff": 3.5,
    "Tern": 2,
    "Favorite points": 91,
    "Kms": 7.91,
    "Country": "Spain",
    "User Data 4": "BarcelonËs",
    ".": 0,
    "Latitude": 41.356312,
    "Longitude": 2.148959
  },
  {
    "Code": "GCKTZF",
    "Placed": "12/10/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFNN",
    "Waypoint_Name": "El Cim d'Estel∑la",
    "Found_by_me": "10/8/2010",
    "Placed By": "pelaroques",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2.5,
    "Tern": 4,
    "Favorite points": 25,
    "Kms": 84.38,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.122017,
    "Longitude": 1.786533
  },
  {
    "Code": "GCKVP0",
    "Placed": "17/10/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "El Pedraforca",
    "Found_by_me": "14/8/2018",
    "Placed By": "pelaroques",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2.5,
    "Tern": 5,
    "Favorite points": 49,
    "Kms": 99.07,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.239083,
    "Longitude": 1.702733
  },
  {
    "Code": "GCKXAW",
    "Placed": "24/10/2004",
    "Corrected Coordinates Indicator": "C",
    "Cache_type": "Multicache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Castell Eramprunya",
    "Found_by_me": "",
    "Placed By": "Elyan (Btt)",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2,
    "Favorite points": 7,
    "Kms": 22.43,
    "Country": "Spain",
    "User Data 4": "Baix Llobregat",
    ".": 0,
    "Latitude": 41.31353333333333,
    "Longitude": 1.9563666666666666
  },
  {
    "Code": "GCKXMF",
    "Placed": "24/10/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Puig d'Arques",
    "Found_by_me": "",
    "Placed By": "CAT's Team",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 1.5,
    "Tern": 2,
    "Favorite points": 17,
    "Kms": 85.29,
    "Country": "Spain",
    "User Data 4": "Baix Empordà",
    ".": 0,
    "Latitude": 41.8892,
    "Longitude": 2.997283
  },
  {
    "Code": "GCM19Y",
    "Placed": "9/11/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Les Penyes Altes",
    "Found_by_me": "29/10/2020",
    "Placed By": "pelaroques",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2.5,
    "Tern": 4,
    "Favorite points": 14,
    "Kms": 101.68,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.302433,
    "Longitude": 1.846083
  },
  {
    "Code": "GCM2D4",
    "Placed": "14/11/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "NFFF",
    "Waypoint_Name": "Martell",
    "Found_by_me": "",
    "Placed By": "Quiet-Tiger and garri & RaCoSerAl",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2.5,
    "Tern": 4,
    "Favorite points": 10,
    "Kms": 27.17,
    "Country": "Spain",
    "User Data 4": "Garraf",
    ".": 0,
    "Latitude": 41.274367,
    "Longitude": 1.923783
  },
  {
    "Code": "GCM5GN",
    "Placed": "27/11/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Abdelazia",
    "Found_by_me": "21/8/2021",
    "Placed By": "Famara",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2.5,
    "Tern": 3,
    "Favorite points": 46,
    "Kms": 105.27,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.25945,
    "Longitude": 0.940083
  },
  {
    "Code": "GCM7KY",
    "Placed": "4/12/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Sta. Bárbara",
    "Found_by_me": "22/8/2020",
    "Placed By": "Famara",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2,
    "Favorite points": 22,
    "Kms": 110.88,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.127133,
    "Longitude": 0.915067
  },
  {
    "Code": "GCM7HW",
    "Placed": "5/12/2004",
    "Corrected Coordinates Indicator": "C",
    "Cache_type": "Multicache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Sant Vicenç de Malla",
    "Found_by_me": "25/8/2020",
    "Placed By": "cipote",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 1.5,
    "Tern": 1.5,
    "Favorite points": 4,
    "Kms": 51.71,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.8866,
    "Longitude": 2.2300166666666668
  },
  {
    "Code": "GCMB80",
    "Placed": "12/12/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "La botifarra perduda",
    "Found_by_me": "19/2/2022",
    "Placed By": "mons&girls",
    "Elevation": 0,
    "Container": "Unknown",
    "Diff": 2.5,
    "Tern": 3,
    "Favorite points": 12,
    "Kms": 27.79,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.639633,
    "Longitude": 2.015833
  },
  {
    "Code": "GCM93M",
    "Placed": "14/12/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "La Cerdanya  (Saneja))",
    "Found_by_me": "13/6/2021",
    "Placed By": "cervino",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 1.5,
    "Tern": 1.5,
    "Favorite points": 3,
    "Kms": 115.04,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 42.435867,
    "Longitude": 1.899167
  },
  {
    "Code": "GCM9H8",
    "Placed": "17/12/2004",
    "Corrected Coordinates Indicator": "C",
    "Cache_type": "Multicache",
    "User flag": "",
    "lg": "FFXF",
    "Waypoint_Name": "Paseo por Castelldefels",
    "Found_by_me": "27/8/2024",
    "Placed By": "EnriKe",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 4,
    "Tern": 3.5,
    "Favorite points": 18,
    "Kms": 23.89,
    "Country": "Spain",
    "User Data 4": "Baix Llobregat",
    ".": 0,
    "Latitude": 41.28665,
    "Longitude": 1.960867
  },
  {
    "Code": "GCMA6M",
    "Placed": "20/12/2004",
    "Corrected Coordinates Indicator": "C",
    "Cache_type": "Multicache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "2 fonts i 1 forn",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 3,
    "Tern": 3,
    "Favorite points": 11,
    "Kms": 86.63,
    "Country": "Spain",
    "User Data 4": "Baix Empordà",
    ".": 0,
    "Latitude": 41.90796,
    "Longitude": 2.998219
  },
  {
    "Code": "GCMCMA",
    "Placed": "31/12/2004",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Webcam Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Port Bó Webcam",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Unknown",
    "Diff": 1.5,
    "Tern": 1.5,
    "Favorite points": 245,
    "Kms": 97.97,
    "Country": "Spain",
    "User Data 4": "Baix Empordà",
    ".": 0,
    "Latitude": 41.888033,
    "Longitude": 3.183683
  },
  {
    "Code": "GCMEF2",
    "Placed": "6/1/2005",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "St. Miquel - Montserrat",
    "Found_by_me": "5/6/2021",
    "Placed By": "Jucar",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2,
    "Favorite points": 36,
    "Kms": 33.64,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.583733,
    "Longitude": 1.84
  },
  {
    "Code": "GCMEPZ",
    "Placed": "7/1/2005",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Multicache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Les Formigues",
    "Found_by_me": "",
    "Placed By": "AlbertCS10 & lluis8, original de palatrecos_team",
    "Elevation": 0,
    "Container": "Small",
    "Diff": 3,
    "Tern": 5,
    "Favorite points": 54,
    "Kms": 99.72,
    "Country": "Spain",
    "User Data 4": "Baix Empordà",
    ".": 0,
    "Latitude": 41.89615,
    "Longitude": 3.201867
  },
  {
    "Code": "GCMJ6A",
    "Placed": "16/1/2005",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "El Fill del Castell",
    "Found_by_me": "",
    "Placed By": "TrencalÚs",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2.5,
    "Tern": 3.5,
    "Favorite points": 15,
    "Kms": 61.39,
    "Country": "Spain",
    "User Data 4": "Selva",
    ".": 0,
    "Latitude": 41.8613,
    "Longitude": 2.6312
  },
  {
    "Code": "GCMP2Z",
    "Placed": "4/2/2005",
    "Corrected Coordinates Indicator": "C",
    "Cache_type": "Multicache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Manresa Tour",
    "Found_by_me": "3/2/2020",
    "Placed By": "kpt",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 4.5,
    "Tern": 2.5,
    "Favorite points": 10,
    "Kms": 50.8,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.795183333333334,
    "Longitude": 1.827966666666667
  },
  {
    "Code": "GCMPPW",
    "Placed": "5/2/2005",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Meià",
    "Found_by_me": "",
    "Placed By": "vicam",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2,
    "Favorite points": 15,
    "Kms": 115.98,
    "Country": "Spain",
    "User Data 4": "Noguera",
    ".": 0,
    "Latitude": 42.0028,
    "Longitude": 1.0208
  },
  {
    "Code": "GCMPTE",
    "Placed": "6/2/2005",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "P. DE LES AIG‹ES (A)",
    "Found_by_me": "18/7/2020",
    "Placed By": "ksalvador",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2.5,
    "Favorite points": 11,
    "Kms": 4.73,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.413367,
    "Longitude": 2.12685
  },
  {
    "Code": "GCMWJR",
    "Placed": "21/2/2005",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Multicache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "Viver i Serrateix",
    "Found_by_me": "7/8/2010",
    "Placed By": "pelaroques",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 3,
    "Tern": 2,
    "Favorite points": 32,
    "Kms": 67.21,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.946067,
    "Longitude": 1.776733
  },
  {
    "Code": "GCMYMJ",
    "Placed": "27/2/2005",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "NNNN",
    "Waypoint_Name": "Castell de La Popa",
    "Found_by_me": "8/12/2018",
    "Placed By": "yahli",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 3,
    "Favorite points": 33,
    "Kms": 39.01,
    "Country": "Spain",
    "User Data 4": "",
    ".": 0,
    "Latitude": 41.773667,
    "Longitude": 2.176633
  },
  {
    "Code": "GCMYWJ",
    "Placed": "28/2/2005",
    "Corrected Coordinates Indicator": "",
    "Cache_type": "Traditional Cache",
    "User flag": "",
    "lg": "FFFF",
    "Waypoint_Name": "La Garrotxa desconeguda",
    "Found_by_me": "",
    "Placed By": "karles",
    "Elevation": 0,
    "Container": "Regular",
    "Diff": 2,
    "Tern": 2.5,
    "Favorite points": 6,
    "Kms": 96.65,
    "Country": "Spain",
    "User Data 4": "Garrotxa",
    ".": 0,
    "Latitude": 42.2667,
    "Longitude": 2.461983
  }
]